<?php

namespace app\module\Admin\modules\User\controllers;


use app\module\Admin\modules\User\models\MUser;
use yii\web\UploadedFile;

class UserController extends \yii\web\Controller
{

    public function actionIndex()
    {
        return $this->render('index');
    }
    public function actions()
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }
    public function actionLogin()
    {
        $loginForm=new MUser();
        $request=\Yii::$app->request;
       if($request->isPost){
           $loginForm->attributes=$request->post("MUser");
           if($loginForm->validate()){

           }

       }
        return $this->render("/default/login",[
            "model"=>$loginForm
        ]);
    }

    /**
     * 设置个人信息
     */
    public function actionAccount(){
        $loginForm=new MUser();
        $request=\Yii::$app->request;
        if($request->isPost){
            $loginForm->attributes=$request->post("MUser");

//            if($loginForm->validate()){
               $loginForm->avatar=UploadedFile::getInstance($loginForm,"avatar");
                if($loginForm->upload()){
//                  return ;
                }
//            }

        }
        return $this->render("/default/account",[
            "model"=>$loginForm
        ]);
    }
}
